REPO_URL: "https://github.com/zeeguu/api.git"
CODE_ROOT_FOLDER: "content/api/"
save_location: "./diagrams"
views:
  - name: "everything_depth_1.html"
    include:
      - "*"
    depth_config:
      root: "*"
      depth: 1

  - name: "everything_depth_1_reflexion.html"
    include:
      - "*"
    allowed_edges_to:
      tools:
      - "zeeguu"
      start:
      - "zeeguu"
      install_stanza_models:
      - "zeeguu"
      zeeguu:
      - "" # nothing
    depth_config:
      root: "*"
      depth: 1
  
  - name: "everything_depth_2_grouped.html"
    include:
      - "*"
    groups: # these would be very unfolded at depth 2 (messy)
      stanza_service:
      - "stanza_service*"
      setup:
      - "setup*"
      asr_service:
      - "asr_service*"
      env_var_defs_default:
      - "env_var_defs_default*"
      tools:
      - "tools*"
      shared_infrastructure:
      - "zeeguu.logging*"
      - "zeeguu.config*"
    depth_config:
      root: "*"
      depth: 2

  - name: "everything_depth_2_grouped_reflexion.html"
    include:
      - "*"
    groups: # these would be very unfolded at depth 2 (messy)
      stanza_service:
      - "stanza_service*"
      setup:
      - "setup*"
      asr_service:
      - "asr_service*"
      env_var_defs_default:
      - "env_var_defs_default*"
      tools:
      - "tools*"
      shared_infrastructure:
      - "zeeguu.logging*"
      - "zeeguu.config*"
    allowed_edges_to:
      tools:
      - "zeeguu.*"
      - "shared_infrastructure"
      start:
      - "zeeguu.api"
      "zeeguu.operations":
      - "zeeguu.*"
      - "shared_infrastructure"
      "zeeguu.cl":
      - "zeeguu.api"
      "zeeguu.api":
      - "zeeguu.core"
      - "shared_infrastructure"
      "zeeguu.core":
      - "shared_infrastructure"
    depth_config:
      root: "*"
      depth: 2
  
  - name: "zeeguu_api.html"
    include:
      - "zeeguu.api.*"
    exclude:
      - "zeeguu.api.app*"
      - "zeeguu.api.cross_domain_app"
      - "zeeguu.api.custom_fmd_graphs"
    groups:
      utils:
        - "zeeguu.api.utils*"
      endpoints:
        - "zeeguu.api.endpoints*"
      test:
        - "zeeguu.api.test*"

  - name: "zeeguu_depth_1.html"
    include:
      - "zeeguu*"
    depth_config:
      root: "zeeguu"
      depth: 2

  - name: "zeeguu_depth_1_reflexion.html"
    include:
      - "zeeguu*"
    groups:
      shared_infrastructure:
        - "zeeguu.logging*"
        - "zeeguu.config*"
    allowed_edges_to:
      "zeeguu.operations":
      - "zeeguu.*"
      - "shared_infrastructure"
      "zeeguu.cl":
      - "zeeguu.api"
      "zeeguu.api":
      - "zeeguu.core"
      - "shared_infrastructure"
      "zeeguu.core":
      - "shared_infrastructure"
    depth_config:
      root: "zeeguu"
      depth: 2

  - name: "zeeguu_depth_1_and_tools.html"
    include:
      - "zeeguu*"
      - "tools*"
    groups:
      tools:
      - "tools*"
    depth_config:
      root: "zeeguu"
      depth: 2

  - name: "zeeguu_depth_1_and_tools_reflexion.html"
    include:
      - "zeeguu*"
      - "tools*"
    groups:
      tools:
        - "tools*"
      shared_infrastructure:
        - "zeeguu.logging*"
        - "zeeguu.config*"
    allowed_edges_to:
      tools:
      - "zeeguu.*"
      - "shared_infrastructure"
      "zeeguu.operations":
      - "zeeguu.*"
      - "shared_infrastructure"
      "zeeguu.cl":
      - "zeeguu.api"
      "zeeguu.api":
      - "zeeguu.core"
      - "shared_infrastructure"
      "zeeguu.core":
      - "shared_infrastructure"
    depth_config:
      root: "zeeguu"
      depth: 2
  
  - name: "zeeguu_depth_2.html"
    include:
      - "zeeguu*"
    exclude:
      - "zeeguu.core.test*"
      - "zeeguu.api.test*"
    depth_config:
      root: "zeeguu"
      depth: 3

  - name: "zeeguu_api_depth_3_endpoints_grouped_and_no_tests.html"
    include:
      - "zeeguu.api*"
    exclude:
      - "zeeguu.api.test*"
    groups:
      endpoints:
      - "zeeguu.api.endpoints*"
    depth_config:
      root: "*"
      depth: 4

  - name: "zeeguu_core_depth_2.html"
    include:
      - "zeeguu.core*"
    depth_config:
      root: "*"
      depth: 3

  